import RootLevelOps from "@/rootLevelOps";
import "./globals.css";
import NextReduxWrapper from "@/redux/NextReduxWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        
        <NextReduxWrapper>
          {children}
        <RootLevelOps/>
        </NextReduxWrapper>
      </body>
    </html>
  );
}
