import RootLevelOps from "@/rootLevelOps";
import "./globals.css";
import NextReduxWrapper from "@/redux/NextReduxWrapper";

import React, { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Suspense>
        <NextReduxWrapper>
          {children}
        <RootLevelOps/>
        </NextReduxWrapper>
        </Suspense>
      </body>
    </html>
  );
}
